# ==============================
# Configuration globale
# ==============================
quarkus.application.name=mini-tb-backend
quarkus.http.port=9001

# ? Active le CORS globalement
quarkus.http.cors=true
# ? Autorise le front-end Vue.js
quarkus.http.cors.origins=http://localhost:5173
# ? Autorise les headers nécessaires
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
# ?? Autorise les méthodes utilisées par ton front
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS
# ? Autorise les cookies si besoin
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.access-log=true

# ==============================
# Datasource / PostgreSQL
# ==============================
quarkus.datasource.db-kind=postgresql
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/minitb
quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/minitb
quarkus.datasource.username=test
quarkus.datasource.password=test123
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# =============================
#  JWT / Security
# =============================
# JWT
#mp.jwt.verify.publickey.location=publicKey.pem
## pour la génération côté backend (signing), quarkus utilisera la privateKey avec smallrye-jwt build
#mp.jwt.signer.private.key.location=META-INF/resources/privateKey.pem

# smallrye.jwt.sign.key-location=classpath:privateKey.pem
# smallrye.jwt.sign.key-algorithm=RS256
# mp.jwt.verify.publickey.location=classpath:publicKey.pem
# mp.jwt.verify.issuer=mini-tb

mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=mini-tb
#smallrye.jwt.sign.key-algorithm=RS256

# Optionnel - durée du token (en secondes)
jwt.expire.seconds=3600

# =============================
#  OpenAPI / Swagger
# =============================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# =============================
#  Logging
# =============================
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.category."com.minitb".level=DEBUG
