# ==============================
# Configuration globale
# ==============================
quarkus.application.name=mini-tb-backend
quarkus.http.port=9001
quarkus.http.access-log=true

# ==============================
# Datasource / PostgreSQL
# ==============================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/minitbdb
quarkus.datasource.username=test
quarkus.datasource.password=test123
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# =============================
#  JWT / Security
# =============================


# =============================
#  OpenAPI / Swagger
# =============================




# =============================
#  Logging
# =============================
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.category."com.minitb".level=DEBUG
